// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StourbridgeFc.Lucky7.Data;

#nullable disable

namespace StourbridgeFc.Lucky7.Data.Migrations
{
    [DbContext(typeof(Lucky7Context))]
    [Migration("20250807171256_AddDateTimeDrawnUtcColumnToDrawWinnersTable")]
    partial class AddDateTimeDrawnUtcColumnToDrawWinnersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTimeDrawCompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_draw_completed_utc");

                    b.Property<DateTime>("DateTimeDrawStartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_draw_started_utc");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_draws");

                    b.ToTable("draws", (string)null);
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.DrawWinner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeDrawnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_drawn_utc");

                    b.Property<int>("DrawId")
                        .HasColumnType("integer")
                        .HasColumnName("draw_id");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<int>("PrizeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("prize_level_id");

                    b.HasKey("Id")
                        .HasName("pk_draw_winners");

                    b.HasIndex("DrawId")
                        .HasDatabaseName("ix_draw_winners_draw_id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_draw_winners_entry_id");

                    b.HasIndex("PrizeLevelId")
                        .HasDatabaseName("ix_draw_winners_prize_level_id");

                    b.ToTable("draw_winners", (string)null);
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_options");

                    b.ToTable("options", (string)null);
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.PrizeLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Winners")
                        .HasColumnType("integer")
                        .HasColumnName("winners");

                    b.HasKey("Id")
                        .HasName("pk_prize_levels");

                    b.ToTable("prize_levels", (string)null);
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.DrawWinner", b =>
                {
                    b.HasOne("StourbridgeFc.Lucky7.Data.Models.Draw", "Draw")
                        .WithMany("DrawWinners")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_draw_winners_draws_draw_id");

                    b.HasOne("StourbridgeFc.Lucky7.Data.Models.Entry", "Entry")
                        .WithMany("DrawWinners")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_draw_winners_entries_entry_id");

                    b.HasOne("StourbridgeFc.Lucky7.Data.Models.PrizeLevel", "PrizeLevel")
                        .WithMany("DrawWinners")
                        .HasForeignKey("PrizeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_draw_winners_prize_levels_prize_level_id");

                    b.Navigation("Draw");

                    b.Navigation("Entry");

                    b.Navigation("PrizeLevel");
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.Draw", b =>
                {
                    b.Navigation("DrawWinners");
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.Entry", b =>
                {
                    b.Navigation("DrawWinners");
                });

            modelBuilder.Entity("StourbridgeFc.Lucky7.Data.Models.PrizeLevel", b =>
                {
                    b.Navigation("DrawWinners");
                });
#pragma warning restore 612, 618
        }
    }
}
